version: "3.9"
services:

  web:
    build: .
    command: "uvicorn run:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/code

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
